services:
  springTech-postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456

  medicine-postgres2:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456

  redis:
    image: redis:8.8.0-alpine3.23
    ports:
      - "6379:6379"

  medicine:
    image: danil2301/medicine:v1
    ports:
      - "8081:8081"
    depends_on:
      - medicine-postgres2

  springtech:
    image: danil2301/springtech:v1
    ports:
      - "8080:8080"
    depends_on:
      - springTech-postgres
      - redis
      - medicine