server:
  port: 8081

spring:
  application:
    name: medicine

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://medicine-postgres2:5432/postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: test

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [Request-ID: %X{requestId}] - %msg%n"